### ISSUE TITLE
Conda env setup

### ISSUE THREAD

**Issue by kezhang-cs** [KeondoPark/votenet_tf#2]
Most packages in requirment.txt could not be found in conda. 
PackagesNotFoundError: The following packages are not available from current channels:
                                                                                                                                 
  - ca-certificates==2021.10.8=ha878542_0                                                                                        
  - certifi==2021.10.8=py38h578d9bd_2                                                                                            
  - typing_extensions==4.1.1=pyha770c72_0                                                                                        
  - lame==3.100=h7f98852_1001                                                                                                    
  - libiconv==1.16=h516909a_0                                                                                                    
  - gnutls==3.6.13=h85f3911_1                                                                                                    
  - keras-nightly==2.5.0.dev2021032900                                                                                           
  - tensorflow-datasets==4.5.2                                                                                                   
  - grpcio==1.34.1                                                                                                               
  - googleapis-common-protos==1.56.1
  - cachetools==4.2.4
  - torchaudio==0.8.1=py38
  - plyfile==0.7.4
  - ffmpeg==4.3=hf484d3e_0
  - torchvision==0.9.1=py38_cpu
  - python_abi==3.8=2_cp38
  - fonttools==4.28.3
  - h5py==3.1.0
  - nettle==3.6=he412f7d_0
  
Could you also share channel of conda and the yml file?
Thanks!

**Comment by KeondoPark** [comment]
Hi, I will tidy up the requirements soon and let you know.
Thanks

**Comment by kezhang-cs** [comment]
Thank you! 
I also have a follow-up question: do you happen to train the model with SunRGBD as well? If so could you include the config file and model as well?

**Comment by KeondoPark** [comment]
Hi, I updated the code, could you try again?
Config files are included in the code base in `configs` folder
I will also try to find a way to include the model checkpoint.

**Comment by kezhang-cs** [comment]
Hi Keondo, Thanks a lot! The new requirement and config works like a charm.
